### ISSUE TITLE
Create Release Notes via milestone closing

### ISSUE THREAD

**Issue by khmarbaise** [khmarbaise/maven-it-extension#317]
```
on:
  milestone:
    types: [closed]
name: Generate Release Notes and Publish
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create release notes from milestone ${{ github.event.milestone.title }}
        uses: docker://decathlon/release-notes-generator-action:2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
      - name: deploy release notes for milestone ${{ github.event.milestone.title }}
        uses: ncipollo/release-action@v1
        with:
          replacesArtifacts: false
          allowUpdates: true
          bodyFile: temp_release_notes/release_file.md
          draft: false
          tag: ${{ github.event.milestone.title }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
```
